FROM swift:4.1
WORKDIR /package
COPY . ./

RUN apt-get update && apt-get install -y wget apt-transport-https software-properties-common python-software-properties && \
wget -q https://repo.vapor.codes/apt/keyring.gpg -O- | apt-key add - && \
echo "deb https://repo.vapor.codes/apt $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/vapor.list && \
apt-get update && \
apt-get install -y libmysqlclient20 libmysqlclient-dev cstack ctls openssl libssl-dev

RUN swift package resolve
RUN swift package clean

CMD ["swift", "--version"]
CMD ["swift", "test"]