# Remember to pick the correct Swift version
FROM swift:4.2.2 as builder
WORKDIR /app/
COPY . .

# Install any dependencies there might be
RUN \
  apt-get -q update && apt-get -q -y install \
  libmysqlclient-dev \
  && rm -r /var/lib/apt/lists/*

# Build the artifacts
RUN mkdir -p /build/lib && cp -R /usr/lib/swift/linux/*.so /build/lib
RUN bash -c "swift build -c release && mv `swift build -c release --show-bin-path` /build/bin"

# Setup new machine to run the artifacts
FROM ubuntu:16.04

# Install any dependencies there might be
RUN \
  apt-get -q update && apt-get -q -y install \
  libatomic1 \
  libbsd0 \
  libcurl3 \
  libicu55 \
  libmysqlclient20 \
  libxml2 \
  && rm -r /var/lib/apt/lists/*
WORKDIR /app/
COPY --from=builder /build/bin .
COPY --from=builder /build/lib/* /usr/lib/
COPY --from=builder /app/Resources ./Resources
COPY --from=builder /app/Public ./Public
EXPOSE 8080

CMD ["./Run","--env=production","--port=8080","--hostname=0.0.0.0"]
