version: '3'
services:
  vapor:
    depends_on:
      - mysql
      - redis
    build: .
    environment:
      - DATABASE_HOSTNAME=mysql
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=vapor
      - DATABASE_PASSWORD=password
      - DATABASE_DB=vapor
      - REDIS_HOSTNAME=redis
    ports:
      - 8080:8080
  mysql:
    image: "mysql:5.7"
    restart: always
    environment:
      - MYSQL_DATABASE=vapor
      - MYSQL_USER=vapor
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 33306:3306
  redis:
    image: "redis:alpine"
